### ISSUE TITLE
HTML Entity in retrieved news text

### ISSUE THREAD

**Issue by Auenc** [techiaith/macsen-flutter#1]
Mae ddrwg gen i am defnyddio Saesneg ond dw i'n dal yn dysgu Cymraeg.

It's possible for a HTML entity/entities to be displayed as text when retrieving news. 

I have noticed `&#8217;` which appears to be an entity representing `'`.

![photo_2021-06-29_13-11-06 1](https://user-images.githubusercontent.com/14826315/123795466-f41e5c80-d8db-11eb-8a64-8725660728e1.png)

Edit: I now realise that the text retrieval is done on the backend. I'll leave this issue up for visibility, but will duplicate it on the other repository.

**Comment by DewiBrynJones** [comment]
Helo, a diolch yn fawr! Gobeithio bod Macsen yn helpu gyda dysgu Cymraeg. 

I've seen the other issue, so I'll close this one.
